[build]
    publish = "dist"
    command = "npm run build"

[[redirects]]
  from = "/images/*"
  to = "https://res.cloudinary.com/dypwsyigo/image/upload/v1583543487/lythfrederiksen-com/:splat"
  status = 200
  force = true